### ISSUE TITLE
Please do not expose your API_KEY

### ISSUE THREAD

**Issue by AaronGulman** [Asjad2515/TECHPLEMENT#1]
Hi,
Here's a quick advice that you may find rather useless since the app is pretty simple ,hence it shouldn't be serious.

However, since you do not explicitly state that people should use their own  API keys , they might simply take advantage of your account on the website the API of which you are using , there are websites that offer a limit number of requests that can be sent to them once you exceed the limit they'll start charging whichever credit card you used to gain access to their API. 

If you want to avoid unexpected charges , there's a better solution: share screenshots of your app and write a short guide for those of us who'd like to use it. I doubt there's a developer that can't take a second to get an API_KEY.

You're doing great ,I am sorry for bothering  and I hope you find this helpful.

**Comment by Asjad2515** [comment]
Thanks for the suggestion
